name: Update OpenSearch API 
on:
  workflow_dispatch:
  schedule:
    - cron: "25 3 * * *"
jobs:
  update-api:
    if: ${{ github.repository == 'saimedhi/opensearch-py' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Config git to rebase
        run: git config --global pull.rebase true
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3.7 -m pip install nox
      - name: Generate API
        run: nox -s generate
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: GitHub App token
        if: ${{ github.repository == 'saimedhi/opensearch-py' }}
        id: github_app_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updated opensearch-py to reflect the latest OpenSearch API spec (${{ steps.date.outputs.date }})
          title: Updated opensearch-py to reflect the latest OpenSearch API spec
          body: |
            Updated [opensearch-py](https://github.com/saimedhi/opensearch-py) to reflect the latest [OpenSearch API spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/OpenSearch.openapi.json)
            Date: ${{ steps.date.outputs.date }}
          branch: automated-api-update
          base: main
          committer: opensearchpy-api-update-bot <noreply@github.com>
          author: opensearchpy-api-update-bot <noreply@github.com>
      - name: Check out update branch
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        run: |
          git fetch origin automated-api-update
          git checkout automated-api-update
      - name: Update CHANGELOG
        uses: jacobtomlinson/gha-find-replace@v3
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        with:
          branch: automated-api-update
          find: "- Your contribution here."
          replace: "Updated opensearch-py to reflect the latest OpenSearch API spec ([#${{steps.cpr.outputs.pull-request-number}}](https://github.com/saimedhi/opensearch-py/pull/${{steps.cpr.outputs.pull-request-number}}))\n- Your contribution here."
          include: "**CHANGELOG.md"
      - name: Commit and Push
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        run: |
          git config --local user.name 'opensearchpy-api-update-bot'
          git config --local user.email 'noreply@github.com'
          git config --local --unset-all http.https://github.com/.extraheader || true
          AUTH=$(echo -n "x-access-token:${{ steps.github_app_token.outputs.token || secrets.GITHUB_TOKEN }}" | base64)
          echo "::add-mask::${AUTH}"
          git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ${AUTH}"
          git add CHANGELOG.md
          git commit --amend --no-edit
          git push origin automated-api-update -f
