name: Update OpenSearch API 
on: [push]
jobs:
  update-api:
    if: ${{ github.repository == 'saimedhi/opensearch-py' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Config git to rebase
        run: git config --global pull.rebase true
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python3.7 -m pip install nox
      - name: Generate API
        run: nox -s generate
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: GitHub App token
        if: ${{ github.repository == 'saimedhi/opensearch-py' }}
        id: github_app_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.CI_APP_ID }}
          private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updated opensearch-py to reflect the latest OpenSearch API spec (${{ steps.date.outputs.date }})
          title: Updated opensearch-py to reflect the latest OpenSearch API spec
          body: |
            Updated [opensearch-py](https://github.com/saimedhi/opensearch-py) to reflect the latest [OpenSearch API spec](https://github.com/opensearch-project/opensearch-api-specification/blob/main/OpenSearch.openapi.json)
            Date: ${{ steps.date.outputs.date }}
          branch: automated-api-update
          base: main
          committer: opensearchpy-api-update-bot <noreply@github.com>
          author: opensearchpy-api-update-bot <noreply@github.com>
      - name: printed
        run: |
          echo "Checking find pattern in CHANGELOG.md..."
          grep -n "Your contribution here." CHANGELOG.md || echo "Pattern not found."
      - name: Update CHANGELOG
        uses: jacobtomlinson/gha-find-replace@v3
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        with:
          find: "Your contribution here."
          replace: "12345678910"
          include: "**CHANGELOG.md"
      - name: List modified files
        run: |
          # Get the list of modified files
          modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          # Print the list of modified files
          echo "Modified files:"
          echo "$modified_files"
      - name: Push changes
        if: ${{ steps.cpr.outputs.pull-request-number != '' }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: automated-api-update
      - name: List modified files2
        run: |
          # Get the list of modified files
          modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          # Print the list of modified files
          echo "Modified files2:"
          echo "$modified_files"
          
